
export default [
    {pack: 'food', title: 'Avocado', id: '1', path: require('../assets/images/avocado.jpg'), price: '2950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Cheesy Pizza', id: '2', path: require('../assets/images/baking.jpg'), price: '3950', desc: 'some description of the item goes here' , eta: '10 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Burrito', id: '3', path: require('../assets/images/burrito.jpg'), price: '4950', desc: 'some description of the item goes here', eta: '20 - 50', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Burger Delight', id: '4', path: require('../assets/images/cheese-burger.jpg'), price: '5950', desc: 'some description of the item goes here', eta: '30 - 60', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Seafood Soup', id: '5', path: require('../assets/images/cooked-seafoods.jpg'), price: '2650', desc: 'some description of the item goes here', eta: '40 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Salad', id: '6', path: require('../assets/images/dessert.jpg'), price: '2930', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Meat Burger', id: '7', path: require('../assets/images/meat-burger.jpg'), price: '2970', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Avocado', id: '8', path: require('../assets/images/avocado.jpg'), price: '3950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Burrito', id: '9', path: require('../assets/images/burrito.jpg'), price: '1950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Cheese Burger', id: '10', path: require('../assets/images/cheese-burger.jpg'), price: '2900', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Seafood Soup', id: '11', path: require('../assets/images/cooked-seafoods.jpg'), price: '4950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Cheesy Pizza', id: '12', path: require('../assets/images/baking.jpg'), price: '5950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Avocado', id: '13', path: require('../assets/images/avocado.jpg'), price: '2950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Cheesy Pizza', id: '14', path: require('../assets/images/baking.jpg'), price: '3950', desc: 'some description of the item goes here' , eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Burrito', id: '15', path: require('../assets/images/burrito.jpg'), price: '4950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Burger Delight', id: '16', path: require('../assets/images/cheese-burger.jpg'), price: '5950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Seafood Soup', id: '17', path: require('../assets/images/cooked-seafoods.jpg'), price: '2650', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Salad', id: '24', path: require('../assets/images/dessert.jpg'), price: '2930', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Meat Burger', id: '18', path: require('../assets/images/meat-burger.jpg'), price: '2970', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Avocado', id: '19', path: require('../assets/images/avocado.jpg'), price: '3950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Burrito', id: '20', path: require('../assets/images/burrito.jpg'), price: '1950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'food', title: 'Cheese Burger', id: '21', path: require('../assets/images/cheese-burger.jpg'), price: '2900', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'leaf', title: 'Seafood Soup', id: '22', path: require('../assets/images/cooked-seafoods.jpg'), price: '4950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
    {pack: 'cart', title: 'Cheesy Pizza', id: '23', path: require('../assets/images/baking.jpg'), price: '5950', desc: 'some description of the item goes here', eta: '20 - 30', rating: '4.9',numRate: '(201)ratings',},
]
